name: VERVORM
favicon: null
layout_spectrum: 0.97759
typography_spectrum: 0.30735534708946943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.4821232247631997
  saturation: 0.2548143286257982
  rhythmicContrast: 0.4062917255796492
purpose: []
